// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLVnZc66VbGVeVHKz2sSFShc3v9DEPU-4',
    appId: '1:309047965543:web:664df8c2753a9c9e89e1c2',
    messagingSenderId: '309047965543',
    projectId: 'fir-auth-with-getx-mvc',
    authDomain: 'fir-auth-with-getx-mvc.firebaseapp.com',
    storageBucket: 'fir-auth-with-getx-mvc.firebasestorage.app',
    measurementId: 'G-T2RPSBXR9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD82D3Dk4IHPtleNgjsuNsoTCHrQ3S6i7E',
    appId: '1:309047965543:android:3f942249bf63a7ae89e1c2',
    messagingSenderId: '309047965543',
    projectId: 'fir-auth-with-getx-mvc',
    storageBucket: 'fir-auth-with-getx-mvc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6pxYpO0jlduBWw5hDd7GWGTTqMF8iEIU',
    appId: '1:309047965543:ios:051491e2ae72ce9f89e1c2',
    messagingSenderId: '309047965543',
    projectId: 'fir-auth-with-getx-mvc',
    storageBucket: 'fir-auth-with-getx-mvc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthGetxMvc',
  );
}
